# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python=3.11.*
  - openpmd-api=0.15.*
  - pandas=2.0.*
  - datashader=0.15.*
  - matplotlib=3.7.*
