[project]
name = "openPMD-resampler"
version = "0.5.1"
description = "A Python package to export particle data from openPMD to text format"
authors = ["Andrei Berceanu <andreicberceanu@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-ppc64le"]

[tasks]
usage = "python usage.py --opmd_path h5/lwfa.h5 --species e_highGamma --reduction_factor 2"
start = "python start.py --opmd_path h5/gas_189394.bp --species e_all --reduction_factor 100"

[dependencies]
python = "3.11.*"
openpmd-api = "0.15.*"
pandas = "2.0.*"
matplotlib = "3.7.*"
datashader = "0.15.*"
